// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE8ETfe-P9pznD8UbMIRraYvCONBrMfYw',
    appId: '1:860227612272:web:22e833d1215a777555ceb5',
    messagingSenderId: '860227612272',
    projectId: 'startup-c1fbf',
    authDomain: 'startup-c1fbf.firebaseapp.com',
    storageBucket: 'startup-c1fbf.appspot.com',
    measurementId: 'G-T5V8GSW9FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1HI2catDDlfemaoWomHkuO4H8OcgopTY',
    appId: '1:860227612272:android:613dc753e0333fe155ceb5',
    messagingSenderId: '860227612272',
    projectId: 'startup-c1fbf',
    storageBucket: 'startup-c1fbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0LFkl6Km_Egv9HmUoJqhTzcBszKbkL8k',
    appId: '1:860227612272:ios:14b3e4080302a60e55ceb5',
    messagingSenderId: '860227612272',
    projectId: 'startup-c1fbf',
    storageBucket: 'startup-c1fbf.appspot.com',
    iosBundleId: 'com.example.startUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0LFkl6Km_Egv9HmUoJqhTzcBszKbkL8k',
    appId: '1:860227612272:ios:9e9ac9c090b7c88155ceb5',
    messagingSenderId: '860227612272',
    projectId: 'startup-c1fbf',
    storageBucket: 'startup-c1fbf.appspot.com',
    iosBundleId: 'com.example.startUp.RunnerTests',
  );
}
